### ISSUE TITLE
Power Bank

### ISSUE THREAD

**Issue by r-enemy** [cjpatoilo/ama#2]
Você poderia me dizer que modelo de Power Bank recomenda?

**Comment by cjpatoilo** [comment]
Fala @r-enemy =D

## Posso dizer qual não recomendar!

**Pineng - Universal USB Backup Power _(Le Fei)_**

Há uma lojinha "xing ling" na Av. Paulista, comprei esse modelo um tempo atrás. Menos de 3 meses de uso ele pifou, pior produto de todos certeza! haha
