### ISSUE TITLE
Shall I join with you in contributing for milligram!!!

### ISSUE THREAD

**Issue by rajasekarm** [cjpatoilo/ama#4]

**Comment by cjpatoilo** [comment]
Hi @rajzshkr Of course, [Milligram](https://github.com/milligram/milligram) is an open source project. Want to contribute? Follow these [recommendations](https://github.com/milligram/milligram/blob/master/contributing.md). I love you contributed to Milligram and help us make it even better! Sometimes it may seem not so easy. There are several ways to help us. I look forward to his contribution, whatever it may be.
