### ISSUE TITLE
What does your dev environment look like? 

### ISSUE THREAD

**Issue by franzejr** [cjpatoilo/ama#6]
Editor, terminal, shell..

**Comment by cjpatoilo** [comment]
Hey @franzejr. This is my setup.:

**Terminal:** 
[HyperTerm](https://hyperterm.org/), 

**Terminal Tools:** 
[Homebrew](https://brew.sh/), 
[Caskroom](https://caskroom.io/), 

**IDE:** 
[Sublime Text](https://sublimetext.com/), 

**IDE Tools:**
[AutoFileName](https://packagecontrol.io/packages/AutoFileName/),
[BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter/),
[Snippets](#),
[Emmet](https://packagecontrol.io/packages/Emmet/),
[ExpandTabsOnSave](https://packagecontrol.io/packages/Expand%20Tabs%20on%20Save/),
[HTML-CSS-JS-Prettify](https://packagecontrol.io/packages/HTML-CSS-JS%20Prettify/),
[LoremIpsum](https://packagecontrol.io/packages/LoremIpsum/),
[Placeholders](https://packagecontrol.io/packages/Placeholders/),
[Tag](https://packagecontrol.io/packages/Tag/),
[Whitespace](https://packagecontrol.io/packages/Whitespace/),

**Version Control:** 
[Git](https://git-scm.com/), 

**Version Control Tools:** 
[GitFlow](https://nvie.com/posts/a-successful-git-branching-model/), 
[SemVer](https://semver.org/), 
[Commit Guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines), 
[SourceTree](https://sourcetreeapp.com), 

**Browser:** 
[Chrome Canary](https://www.google.com/chrome/browser/canary.html),

**Browser Tools:** 
[DevTools](https://developer.chrome.com/devtools/), 
[Postman](https://chrome.google.com/webstore/detail/postman-launcher/igofndmniooofoabmmpfonmdnhgchoka?hl=en), 
[LightHouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en), 
[WhatsFont](https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm?hl=en/), 
[CacheKiller](https://chrome.google.com/webstore/detail/cache-killer/jpfbieopdmepaolggioebjmedmclkbap?hl=en), 
[Image Download](https://domain.com/), 
[ColorZilla](https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp?hl=en), 
[Batarang](https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk?hl=en), 
[Wappalyzer](https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg?hl=en),

**Playground:** 
[Codepen](https://codepen.io/), 

**Mockup Tools:** 
[Balsamiq](https://balsamiq.com/), 

**Design Tools:** 
[Sketch](https://www.sketchapp.com/), 
[Photoshop](http://www.adobe.com/products/photoshop.html), 
[Illustrator](http://www.adobe.com/products/illustrator.html), 


..and you, what is your setup?
